[package]
name = "bevy_wasm_window_resize"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Leinnan/bevy_wasm_window_resize"
homepage = "https://github.com/Stazis555/bevy_wasm_window_resize"
readme = "README.md"
license = "MIT"
keywords = ["bevy", "diagnostic", "game", "log", "fps"]
categories  = ["game-engines"]

[dependencies]
bevy = "0.10.0"
