[package]
name = "bevy_wasm_window_resize"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Leinnan/bevy_wasm_window_resize"
homepage = "https://github.com/Stazis555/bevy_wasm_window_resize"
readme = "README.md"
license = "MIT"
keywords = ["bevy", "wasm", "web", "game"]
categories  = ["game-engines"]
description = "Bevy helper crate that makes application canvas match window size."

[dependencies]
bevy = "0.10.0"
